apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "external.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "external.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "external.name" . }}
    spec:
      containers:
        - name: alpine
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "sleep", "infinity" ]
