apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: alpine
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "sleep", "infinity" ]
